export type RenderMode='mesh'|'particles';
export interface CosmosRenderer {draw(dt:number):void;resize():void;reset():void;explode(x?:number,y?:number):number;dispose():void;yaw:number;pitch:number;distance:number;auto:boolean;jitter:boolean;paused:boolean;points:boolean;frames:number;explosions:number;}
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
const rotation=`uniform vec2 u_angle;uniform float u_distance,u_aspect;vec3 rotate(vec3 p){float c=cos(u_angle.x),s=sin(u_angle.x);p=vec3(p.x*c+p.z*s,p.y,-p.x*s+p.z*c);c=cos(u_angle.y);s=sin(u_angle.y);return vec3(p.x,p.y*c-p.z*s,p.y*s+p.z*c);}vec4 project(vec3 p){float w=u_distance-p.z;return vec4(p.x*2.414/u_aspect,p.y*2.414,1.002*w-.2002,w);}`;
const cache=new Map<string,Promise<ArrayBuffer>>();
export function loadCosmosBuffer(src:string):Promise<ArrayBuffer>{
 if(!cache.has(src))cache.set(src,(async()=>{const response=await fetch(src);if(!response.ok)throw Error('Model unavailable');const bytes=await response.arrayBuffer();const head=new Uint8Array(bytes);if(head[0]!==31||head[1]!==139)return bytes;return new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();})().catch(error=>{cache.delete(src);throw error;}));
 return cache.get(src)!;
}
export function createCosmosRenderer(canvas:HTMLCanvasElement,mode:RenderMode,bytes:ArrayBuffer):CosmosRenderer{
 const context=canvas.getContext('webgl',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!context)throw Error('WebGL unavailable');const gl=context;
 const programs:WebGLProgram[]=[],buffers:WebGLBuffer[]=[];let disposed=false,aspect=1,dpr=1,time=0,accumulator=0,fitDistance=mode==='mesh'?5.2:4.8;
 function program(vertex:string,fragment:string){const p=gl.createProgram()!;for(const [type,source] of [[gl.VERTEX_SHADER,vertex],[gl.FRAGMENT_SHADER,fragment]] as const){const s=gl.createShader(type)!;gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)??'Shader error');gl.attachShader(p,s);gl.deleteShader(s);}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p)??'Program error');programs.push(p);return p;}
 function buffer(data:ArrayBufferView,type:number=gl.ARRAY_BUFFER,usage:number=gl.STATIC_DRAW){const b=gl.createBuffer()!;gl.bindBuffer(type,b);gl.bufferData(type,data,usage);buffers.push(b);return b;}
 const uniforms=new Map<WebGLProgram,Map<string,WebGLUniformLocation|null>>(),attributes=new Map<WebGLProgram,Map<string,number>>();
 function location(p:WebGLProgram,name:string){if(!uniforms.has(p))uniforms.set(p,new Map());const cache=uniforms.get(p)!;if(!cache.has(name))cache.set(name,gl.getUniformLocation(p,name));return cache.get(name)!;}
 function attributeLocation(p:WebGLProgram,name:string){if(!attributes.has(p))attributes.set(p,new Map());const cache=attributes.get(p)!;if(!cache.has(name))cache.set(name,gl.getAttribLocation(p,name));return cache.get(name)!;}
 function attribute(p:WebGLProgram,name:string,b:WebGLBuffer,size:number,type:number,normalized=false,stride=0){const a=attributeLocation(p,name);gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,size,type,normalized,stride,0);}
 function uniform(p:WebGLProgram,name:string,n:number){gl.uniform1f(location(p,name),n);}
 function camera(p:WebGLProgram){gl.useProgram(p);gl.uniform2f(location(p,'u_angle'),renderer.yaw,renderer.pitch);uniform(p,'u_distance',renderer.distance);uniform(p,'u_aspect',aspect);}
 const flat=program(`attribute vec3 a_position;attribute vec4 a_color;varying vec4 v_color;${rotation}void main(){gl_Position=project(rotate(a_position));v_color=a_color;}`,`precision mediump float;varying vec4 v_color;void main(){gl_FragColor=v_color;}`);
 const renderer:CosmosRenderer={yaw:mode==='mesh'?-.65:0,pitch:mode==='mesh'?.58:0,distance:mode==='mesh'?5.2:4.8,auto:mode==='particles',jitter:true,paused:false,points:false,frames:0,explosions:0,draw:()=>{},resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio,mode==='mesh'?1.25:1.7);const w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(canvas.width===w&&canvas.height===h)return;canvas.width=w;canvas.height=h;aspect=r.width/Math.max(1,r.height);const fit=(mode==='mesh'?5.2:4.8)*Math.max(1,(mode==='mesh'?1.3:1)/aspect);if(Math.abs(renderer.distance-fitDistance)<.001)renderer.distance=fit;fitDistance=fit;gl.viewport(0,0,canvas.width,canvas.height);},reset(){renderer.yaw=mode==='mesh'?-.65:0;renderer.pitch=mode==='mesh'?.58:0;renderer.distance=fitDistance;},explode:()=>0,dispose(){disposed=true;buffers.forEach(b=>gl.deleteBuffer(b));programs.forEach(p=>gl.deleteProgram(p));gl.getExtension('WEBGL_lose_context')?.loseContext();}};
 const lines:number[]=[],lineColors:number[]=[];
 function line(a:number[],b:number[],color:number[]){lines.push(...a,...b);lineColors.push(...color,...color);}
 if(mode==='mesh'){
  const header=new Uint32Array(bytes,0,4);if(header[0]!==0x4d534f43||header[1]!==1||!gl.getExtension('OES_element_index_uint'))throw Error('Unsupported model');const n=header[2],count=header[3];
  if(bytes.byteLength!==16+n*12+count*4)throw Error('Incomplete mesh');
  const p=buffer(new Uint16Array(bytes,16,n*3)),norm=buffer(new Int8Array(bytes,16+n*6,n*3)),col=buffer(new Uint8Array(bytes,16+n*9,n*3)),idx=buffer(new Uint32Array(bytes,16+n*12,count),gl.ELEMENT_ARRAY_BUFFER);
  const material=program(`attribute vec3 a_position,a_normal,a_color;varying vec3 v_normal,v_color;uniform float u_pointSize;${rotation}void main(){vec3 p=(a_position-.5)*4.;gl_Position=project(rotate(p));gl_PointSize=u_pointSize;v_normal=rotate(a_normal);v_color=a_color;}`,`precision mediump float;varying vec3 v_normal,v_color;uniform float u_points;void main(){if(u_points>.5&&length(gl_PointCoord-.5)>.47)discard;vec3 n=normalize(v_normal);if(!gl_FrontFacing)n=-n;float light=.35+.52*max(0.,dot(n,normalize(vec3(-.45,.8,1.2))))+.13*max(0.,dot(n,normalize(vec3(.8,.3,-.8))));gl_FragColor=vec4(v_color*light,1.);}`);
  for(let i=-15;i<=15;i++){const v=i/10;line([-1.5,-.5,v],[1.5,-.5,v],[.54,.55,.60,.14]);line([v,-.5,-1.5],[v,-.5,1.5],[.54,.55,.60,.14]);}
  const lp=buffer(new Float32Array(lines)),lc=buffer(new Float32Array(lineColors));
  renderer.draw=(dt)=>{if(disposed)return;if(renderer.auto&&!renderer.paused)renderer.yaw+=dt*.18;gl.clearColor(.965,.965,.975,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.disable(gl.BLEND);camera(material);const step=renderer.points?Math.ceil(n/40000):1;attribute(material,'a_position',p,3,gl.UNSIGNED_SHORT,true,step*6);attribute(material,'a_normal',norm,3,gl.BYTE,true,step*3);attribute(material,'a_color',col,3,gl.UNSIGNED_BYTE,true,step*3);uniform(material,'u_pointSize',1.45*dpr);uniform(material,'u_points',renderer.points?1:0);if(renderer.points)gl.drawArrays(gl.POINTS,0,Math.floor(n/step));else{gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,idx);gl.drawElements(gl.TRIANGLES,count,gl.UNSIGNED_INT,0);}gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);camera(flat);attribute(flat,'a_position',lp,3,gl.FLOAT);attribute(flat,'a_color',lc,4,gl.FLOAT);gl.drawArrays(gl.LINES,0,lines.length/3);renderer.frames++;};
 }else{
  const base=new Float32Array(bytes),positions=base.slice(),vel=new Float32Array(base.length),colors=new Float32Array(base.length).fill(220/255),count=base.length/3;let springFrames=0,pointsDirty=false,trailsDirty=true;
  const points=program(`attribute vec3 a_position,a_base,a_color;varying vec3 v_color;uniform float u_time,u_jitter,u_size;${rotation}void main(){float noise=sin(dot(a_base,vec3(16.7,12.1,19.3))+u_time)*sin(a_base.x*11.1+u_time*.6);vec3 p=a_position+normalize(a_base+vec3(.0001))*noise*.002*u_jitter;gl_Position=project(rotate(p));gl_PointSize=u_size;v_color=a_color;}`,`precision mediump float;varying vec3 v_color;void main(){float r=length(gl_PointCoord-.5);if(r>.5)discard;gl_FragColor=vec4(v_color,.85);}`);
  const pb=buffer(positions,gl.ARRAY_BUFFER,gl.DYNAMIC_DRAW),bb=buffer(base),cb=buffer(colors,gl.ARRAY_BUFFER,gl.DYNAMIC_DRAW);
  const corners=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]];for(const [a,b] of [[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]])line(corners[a],corners[b],[.42,.44,.48,.42]);
  const lp=buffer(new Float32Array(lines)),lc=buffer(new Float32Array(lineColors));
  type Vine={p:number[];v:number[];target:number[];life:number;trail:number[][]};const vines:Vine[]=Array.from({length:160},()=>({p:[],v:[],target:[],life:0,trail:[]}));
  function respawn(v:Vine){const face=Math.floor(Math.random()*6),a=Math.random()*2-1,b=Math.random()*2-1;v.p=[a,b,face%2?1:-1];if(face<2)v.p=[face%2?1:-1,a,b];else if(face<4)v.p=[a,face%2?1:-1,b];v.v=[0,0,0];const k=Math.floor(Math.random()*count)*3;v.target=[base[k],base[k+1],base[k+2]];v.life=140+Math.random()*120;v.trail=[v.p.slice()];}vines.forEach(respawn);
  const trailPositions=new Float32Array(160*54*6),trailColors=new Float32Array(160*54*8),vp=buffer(trailPositions,gl.ARRAY_BUFFER,gl.DYNAMIC_DRAW),vc=buffer(trailColors,gl.ARRAY_BUFFER,gl.DYNAMIC_DRAW);let trailCount=0;
  function update(){trailsDirty=true;time+=.01;if(renderer.auto){renderer.yaw+=.0032;renderer.pitch+=.0016;}
   if(springFrames>0){pointsDirty=true;for(let k=0;k<positions.length;k++){vel[k]=(vel[k]+(base[k]-positions[k])*.05)*.9;positions[k]+=vel[k];colors[k]+=(220/255-colors[k])*.05;}springFrames--;}
   for(const v of vines){const delta=v.target.map((p,i)=>p-v.p[i]),distance=Math.hypot(...delta);for(let i=0;i<3;i++){v.v[i]+=delta[i]/Math.max(distance,.0001)*.0011+Math.sin(v.p[i]*2+time*.5+i*100)*.0008;}const speed=Math.hypot(...v.v),limit=Math.min(1,.012/Math.max(speed,.0001));for(let i=0;i<3;i++){v.v[i]*=limit*.93;v.p[i]+=v.v[i];}v.trail.push(v.p.slice());if(v.trail.length>55)v.trail.shift();if(--v.life<=0||distance<.03)respawn(v);}
  }
  function trails(){if(!trailsDirty)return;trailsDirty=false;trailCount=0;for(const v of vines)for(let j=1;j<v.trail.length;j++){for(let endpoint=0;endpoint<2;endpoint++){const t=(j-1+endpoint)/(v.trail.length-1),p=v.trail[j-1+endpoint];trailPositions.set(p,trailCount*3);const color=trailCount*4;trailColors[color]=1-(175/255)*t;trailColors[color+1]=80/255+20/255*t;trailColors[color+2]=80/255+175/255*t;trailColors[color+3]=(20+160*t)/255;trailCount++;}}gl.bindBuffer(gl.ARRAY_BUFFER,vp);gl.bufferSubData(gl.ARRAY_BUFFER,0,trailPositions);gl.bindBuffer(gl.ARRAY_BUFFER,vc);gl.bufferSubData(gl.ARRAY_BUFFER,0,trailColors);}
  renderer.explode=(x=.5,y=.5)=>{let nearest=0,best=Infinity;const r=canvas.getBoundingClientRect(),cy=Math.cos(renderer.yaw),sy=Math.sin(renderer.yaw),cx=Math.cos(renderer.pitch),sx=Math.sin(renderer.pitch);for(let k=0;k<positions.length;k+=3){const px=positions[k]*cy+positions[k+2]*sy,pz=-positions[k]*sy+positions[k+2]*cy,py=positions[k+1]*cx-pz*sx,z=positions[k+1]*sx+pz*cx,w=renderer.distance-z;const dx=(.5+px*2.414/aspect/w*.5-x)*r.width,dy=(.5-py*2.414/w*.5-y)*r.height,d=dx*dx+dy*dy;if(d<best){best=d;nearest=k;}}const center=positions.slice(nearest,nearest+3);let affected=0;for(let k=0;k<positions.length;k+=3){let dx=positions[k]-center[0],dy=positions[k+1]-center[1],dz=positions[k+2]-center[2],distance=Math.hypot(dx,dy,dz);if(distance>=.5)continue;affected++;if(distance<.00001){dx=Math.random()-.5;dy=Math.random()-.5;dz=Math.random()-.5;distance=Math.hypot(dx,dy,dz);}const strength=(.06-clamp(distance/.5,0,1)*.045)/distance;vel[k]+=dx*strength;vel[k+1]+=dy*strength;vel[k+2]+=dz*strength;const red=Math.random()<.5;colors[k]=red?1:(60+Math.random()*100)/255;colors[k+1]=(60+Math.random()*100)/255;colors[k+2]=red?(60+Math.random()*100)/255:1;}pointsDirty=true;springFrames=360;renderer.explosions++;renderer.paused=false;return affected;};
  const reset=renderer.reset;renderer.reset=()=>{reset();pointsDirty=trailsDirty=true;positions.set(base);vel.fill(0);colors.fill(220/255);springFrames=0;time=0;vines.forEach(respawn);};
  renderer.draw=(dt)=>{if(disposed)return;if(!renderer.paused){accumulator+=Math.min(.05,dt);while(accumulator>=1/60){update();accumulator-=1/60;}}gl.clearColor(5/255,5/255,5/255,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.disable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);camera(flat);attribute(flat,'a_position',lp,3,gl.FLOAT);attribute(flat,'a_color',lc,4,gl.FLOAT);gl.drawArrays(gl.LINES,0,lines.length/3);trails();camera(flat);attribute(flat,'a_position',vp,3,gl.FLOAT);attribute(flat,'a_color',vc,4,gl.FLOAT);gl.drawArrays(gl.LINES,0,trailCount);if(pointsDirty){gl.bindBuffer(gl.ARRAY_BUFFER,pb);gl.bufferSubData(gl.ARRAY_BUFFER,0,positions);gl.bindBuffer(gl.ARRAY_BUFFER,cb);gl.bufferSubData(gl.ARRAY_BUFFER,0,colors);pointsDirty=false;}camera(points);attribute(points,'a_position',pb,3,gl.FLOAT);attribute(points,'a_base',bb,3,gl.FLOAT);attribute(points,'a_color',cb,3,gl.FLOAT);uniform(points,'u_time',time);uniform(points,'u_jitter',renderer.jitter?1:0);uniform(points,'u_size',Math.max(1.1,canvas.clientWidth/800)*dpr);gl.drawArrays(gl.POINTS,0,count);renderer.frames++;};
 }
 renderer.resize();return renderer;
}


