export type AudioSignal={level:number;bass:number;treble:number};
export type MetRenderer={draw:(time:number,signal:AudioSignal,yaw:number,pitch:number)=>void;resize:()=>void;dispose:()=>void};
export async function loadMetamorphosisPoints(src:string,signal:AbortSignal){
 const response=await fetch(src,{signal});if(!response.ok||!response.body)throw Error('Model unavailable');
 const bytes=await response.arrayBuffer(),head=new Uint8Array(bytes);const buffer=head[0]===31&&head[1]===139?await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer():bytes;
 const positions=new Float32Array(buffer);if(positions.length!==48000*3)throw Error('Incomplete model');return positions;
}
export async function createMetamorphosisRenderer(canvas:HTMLCanvasElement,positions:Float32Array,background:string):Promise<MetRenderer>{
 const gl=canvas.getContext('webgl',{alpha:false,antialias:false,powerPreference:'low-power'});if(!gl)throw Error('WebGL unavailable');
 const programs:WebGLProgram[]=[],shaders:WebGLShader[]=[],buffers:WebGLBuffer[]=[],textures:WebGLTexture[]=[];
 const compile=(type:number,source:string)=>{const s=gl.createShader(type)!;gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)??'Shader error');shaders.push(s);return s;};
 const program=(vertex:string,fragment:string)=>{const p=gl.createProgram()!;gl.attachShader(p,compile(gl.VERTEX_SHADER,vertex));gl.attachShader(p,compile(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p)??'Program error');programs.push(p);return p;};
 const bg=program(`attribute vec2 a_position;varying mediump vec2 v_uv;void main(){v_uv=a_position*.5+.5;gl_Position=vec4(a_position,0.,1.);}`,`precision mediump float;varying mediump vec2 v_uv;uniform sampler2D u_image;uniform float u_time,u_level,u_aspect,u_imageAspect;void main(){vec2 uv=v_uv;float ratio=u_aspect/u_imageAspect;if(ratio>1.)uv.y=(uv.y-.5)/ratio+.5;else uv.x=(uv.x-.5)*ratio+.5;float wave=sin(uv.y*13.+u_time*.42)*sin(uv.x*9.-u_time*.28);uv+=vec2(sin(uv.y*10.+u_time*.36),wave)*(.008+u_level*.018);vec3 color=texture2D(u_image,uv).rgb;float vignette=1.-smoothstep(.28,.78,length(v_uv-.5));gl_FragColor=vec4(color*(.54+u_level*.16)*(.42+vignette*.58),1.);}`);
 const particles=program(`precision highp float;attribute vec4 a_point;uniform mediump float u_time,u_level,u_bass,u_treble,u_aspect,u_yaw,u_pitch,u_dpr,u_glow,u_layer;varying mediump float v_alpha,v_seed,v_layer;float hash(float x){return fract(sin(x*123.719)*43758.5453);}void main(){float seed=a_point.w;vec3 p=a_point.xyz;float a=hash(seed+3.),b=hash(seed+19.),c=hash(seed+71.);float t=u_time;vec3 n=vec3(sin(p.y*11.+t*.9+a*6.28),cos(p.x*9.-t*.7+b*6.28),sin(p.z*12.+t*.65+c*6.28));if(u_layer<.5){p+=n*(.003+u_level*.09);p*=1.+u_level;}else{float phase=fract(t*(.05+.04*b)+a);float spread=phase*(.2+u_level*2.4+u_bass*.2);vec3 direction=normalize(vec3(p.xy*.7+vec2(cos(a*6.28),sin(a*6.28))*.5,sin(b*6.28)*.3));p+=direction*spread+n*(.03+u_level*.12);p.xy+=vec2(sin(t*.6+b*8.),cos(t*.4+a*8.))*spread*.15;v_alpha=sin(phase*3.14159)*(.1+u_level*.75);}float cy=cos(u_yaw),sy=sin(u_yaw),cx=cos(u_pitch),sx=sin(u_pitch);p=vec3(p.x*cy+p.z*sy,p.y,-p.x*sy+p.z*cy);p=vec3(p.x,p.y*cx-p.z*sx,p.y*sx+p.z*cx);float perspective=2.6/(2.6-p.z*.35);gl_Position=vec4(p.x*.63*perspective/u_aspect,p.y*.63*perspective,0.,1.);gl_PointSize=(u_glow>.5?9.+u_level*9.:1.1+u_level*1.6+u_treble*1.2)*u_dpr;if(u_layer<.5)v_alpha=.4+u_level*.55;v_alpha*=u_glow>.5?.07:.75;v_seed=a;v_layer=u_layer;}`,
 `precision mediump float;varying mediump float v_alpha,v_seed,v_layer;uniform mediump float u_level,u_glow;void main(){float r=length(gl_PointCoord*2.-1.);if(r>1.)discard;float alpha=(u_glow>.5?exp(-r*r*5.):1.-smoothstep(.25,1.,r))*v_alpha;vec3 cyan=vec3(.24,.77,.92),white=vec3(.78,.9,.98);vec3 color=mix(cyan,white,v_layer>.5?.75:smoothstep(.65,1.,v_seed));gl_FragColor=vec4(color,alpha);}`);
 const buffer=(data:Float32Array)=>{const b=gl.createBuffer()!;gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);buffers.push(b);return b;};
 const quad=buffer(new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1])),points=new Float32Array(48000*4);
 for(let i=0;i<48000;i++){points.set(positions.subarray(i*3,i*3+3),i*4);points[i*4+3]=i+.37;}
 const cloud=buffer(points),texture=gl.createTexture()!;textures.push(texture);gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,1,1,0,gl.RGB,gl.UNSIGNED_BYTE,new Uint8Array([3,6,10]));
 const image=new Image();image.src=background;try{await image.decode();gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,gl.RGB,gl.UNSIGNED_BYTE,image);}catch{}
 gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);
 const locations=new Map<string,WebGLUniformLocation|null>();const uni=(p:WebGLProgram,name:string,value:number)=>{const key=programs.indexOf(p)+name;if(!locations.has(key))locations.set(key,gl.getUniformLocation(p,name));gl.uniform1f(locations.get(key)!,value);};
 let aspect=1,dpr=1,disposed=false;const resize=()=>{dpr=Math.min(devicePixelRatio||1,1.5,1800/Math.max(1,canvas.clientWidth));const width=Math.max(1,Math.round(canvas.clientWidth*dpr)),height=Math.max(1,Math.round(canvas.clientHeight*dpr));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}aspect=width/height;gl.viewport(0,0,width,height);};resize();
 return {resize,draw(time,signal,yaw,pitch){if(disposed)return;gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.useProgram(bg);gl.bindBuffer(gl.ARRAY_BUFFER,quad);const a=gl.getAttribLocation(bg,'a_position');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,texture);gl.uniform1i(gl.getUniformLocation(bg,'u_image'),0);uni(bg,'u_time',time);uni(bg,'u_level',signal.level);uni(bg,'u_aspect',aspect);uni(bg,'u_imageAspect',(image.naturalWidth||16)/(image.naturalHeight||9));gl.drawArrays(gl.TRIANGLES,0,6);gl.disableVertexAttribArray(a);
 gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.useProgram(particles);gl.bindBuffer(gl.ARRAY_BUFFER,cloud);const point=gl.getAttribLocation(particles,'a_point');gl.enableVertexAttribArray(point);gl.vertexAttribPointer(point,4,gl.FLOAT,false,0,0);
 for(const [name,value] of Object.entries({u_time:time,u_level:signal.level,u_bass:signal.bass,u_treble:signal.treble,u_aspect:aspect,u_yaw:yaw,u_pitch:pitch,u_dpr:dpr}))uni(particles,name,value);
 uni(particles,'u_layer',0);uni(particles,'u_glow',1);gl.drawArrays(gl.POINTS,0,32000);uni(particles,'u_glow',0);gl.drawArrays(gl.POINTS,0,32000);uni(particles,'u_layer',1);gl.drawArrays(gl.POINTS,32000,16000);gl.disableVertexAttribArray(point);
 },dispose(){disposed=true;for(const b of buffers)gl.deleteBuffer(b);for(const t of textures)gl.deleteTexture(t);for(const p of programs)gl.deleteProgram(p);for(const s of shaders)gl.deleteShader(s);}};
}


