import {createMetamorphosisRenderer,loadMetamorphosisPoints,type AudioSignal,type MetRenderer} from './metamorphosis-renderer';
let active:HTMLElement|null=null,disposeAll:(()=>void)|null=null;
export function initializeMetamorphosisInteraction(){
 const root=document.querySelector<HTMLElement>('[data-met-interaction]');if(root===active)return;disposeAll?.();active=root;if(!root)return;
 const canvas=root.querySelector<HTMLCanvasElement>('canvas')!,status=root.querySelector<HTMLElement>('[data-met-status]')!,abort=new AbortController(),zh=document.documentElement.lang.startsWith('zh');
 const buttons=[...root.querySelectorAll<HTMLButtonElement>('[data-met-action]')],file=root.querySelector<HTMLInputElement>('[data-met-file]')!,sensitivity=root.querySelector<HTMLInputElement>('[data-met-sensitivity]')!,volume=root.querySelector<HTMLInputElement>('[data-met-volume]')!,bars=[...root.querySelectorAll<HTMLElement>('.met-spectrum i')],readout=root.querySelector<HTMLOutputElement>('[data-met-level]')!;
 const say=(cn:string,en:string)=>status.textContent=zh?cn:en;
 let renderer:MetRenderer|null=null,dead=false,visible=false,loading=false,paused=matchMedia('(prefers-reduced-motion:reduce)').matches,raf=0,last=0,time=0,frames=0,lastReadout=0,yaw=0,pitch=0,suspended=false;
 let context:AudioContext|null=null,analyser:AnalyserNode|null=null,monitor:GainNode|null=null,stream:MediaStream|null=null,schedule:ReturnType<typeof setInterval>|null=null,audioGeneration=0;
 const nodes:AudioNode[]=[],signal:AudioSignal={level:0,bass:0,treble:0},wave=new Float32Array(2048),frequencies=new Uint8Array(1024);
 function sync(){for(const b of buttons){const name=b.dataset.metAction;if(name==='microphone')b.setAttribute('aria-pressed',String(root!.dataset.audioMode==='microphone'));if(name==='pause'){b.setAttribute('aria-pressed',String(paused));b.textContent=paused?(zh?'恢复画面':'Resume visuals'):(zh?'暂停画面':'Pause visuals');}b.disabled=!renderer||(name==='stop'&&root!.dataset.audioMode==='idle')||(root!.dataset.audioMode==='waiting'&&['demo','microphone'].includes(name!));}file.disabled=!renderer||root!.dataset.audioMode==='waiting';}
 function stopAudio(announce=true){audioGeneration++;if(schedule){clearInterval(schedule);schedule=null;}stream?.getTracks().forEach(track=>track.stop());stream=null;for(const node of nodes.splice(0)){try{if('stop' in node)(node as AudioScheduledSourceNode).stop();node.disconnect();}catch{}}if(context)void context.close().catch(()=>{});context=null;analyser=null;monitor=null;wave.fill(0);frequencies.fill(0);signal.level=signal.bass=signal.treble=0;readout.value='0.00';root!.dataset.signalLevel='0.000';for(const bar of bars)bar.style.transform='scaleY(.025)';root!.dataset.audioMode='idle';sync();render();if(announce)say('声音已停止，可选择新的输入','Audio stopped. Choose another input.');}
 async function setupAudio(){stopAudio(false);const generation=audioGeneration,ctx=new AudioContext();context=ctx;analyser=ctx.createAnalyser();analyser.fftSize=2048;analyser.smoothingTimeConstant=.7;monitor=ctx.createGain();monitor.gain.value=Number(volume.value)/100;root!.dataset.audioMode="waiting";sync();await ctx.resume();return generation;}
 function meter(dt:number){let energy=0,bass=0,treble=0;if(analyser){analyser.getFloatTimeDomainData(wave);for(const value of wave)energy+=value*value;energy=Math.min(1,Math.sqrt(energy/wave.length)*5*Number(sensitivity.value));analyser.getByteFrequencyData(frequencies);for(let i=0;i<24;i++)bass+=frequencies[i]/255/24;for(let i=80;i<300;i++)treble+=frequencies[i]/255/220;}const blend=1-Math.exp(-dt/.22);signal.level+=(energy-signal.level)*blend;signal.bass+=(bass-signal.bass)*blend;signal.treble+=(treble-signal.treble)*blend;}
 function render(){if(!raf&&!dead&&visible&&!suspended&&!document.hidden)raf=requestAnimationFrame(frame);}
 function frame(now:number){raf=0;if(dead||!renderer||!visible||suspended||document.hidden)return;const dt=last?Math.min(.06,(now-last)/1000):1/30;if(last&&now-last<30){render();return;}last=now;if(!paused)time+=dt;meter(dt);renderer.draw(time,signal,yaw,pitch);frames++;
 if(now-lastReadout>120){lastReadout=now;readout.value=signal.level.toFixed(2);root!.dataset.signalLevel=signal.level.toFixed(3);root!.dataset.frames=String(frames);root!.dataset.yaw=yaw.toFixed(3);for(let i=0;i<bars.length;i++){const begin=Math.round(Math.pow(i/bars.length,2)*512),end=Math.max(begin+1,Math.round(Math.pow((i+1)/bars.length,2)*512));let value=0;for(let k=begin;k<end;k++)value+=frequencies[k]??0;bars[i].style.transform=`scaleY(${Math.max(.025,value/(end-begin)/255)})`;}}
 if(!paused||analyser)render();
 }
 async function load(){if(renderer||loading||dead)return;loading=true;say('正在载入原始模型','Loading the original model');try{const points=await loadMetamorphosisPoints(root!.dataset.source!,abort.signal);if(dead)return;const next=await createMetamorphosisRenderer(canvas,points,root!.dataset.background!);if(dead){next.dispose();return;}renderer=next;root!.dataset.state='ready';canvas.setAttribute('aria-busy','false');sync();say('选择声音输入，开始体验','Choose an audio source to begin');render();}catch(error){if(dead)return;console.warn('Metamorphosis scene:',error);root!.dataset.state='error';canvas.setAttribute('aria-busy','false');say('当前设备无法加载交互，可观看下方原始动态影像','The interactive scene is unavailable; watch the original film below.');}finally{loading=false;}}
 async function demo(){try{const generation=await setupAudio();if(dead||generation!==audioGeneration)return;const ctx=context!,input=ctx.createGain();input.gain.value=.8;input.connect(analyser!);analyser!.connect(monitor!);monitor!.connect(ctx.destination);nodes.push(input);root!.dataset.audioMode='demo';paused=false;sync();let beat=0,next=ctx.currentTime+.03;
 const tick=()=>{if(dead||generation!==audioGeneration||document.hidden||suspended||!visible)return;next=Math.max(next,ctx.currentTime+.02);while(next<ctx.currentTime+.2){const note=[130.81,164.81,196,261.63,196,164.81,146.83,196][beat%8];for(const [frequency,gain] of [[note,.22],[note*1.5,.10],[beat%2===0?55:82.41,.25]]){const oscillator=ctx.createOscillator(),envelope=ctx.createGain();oscillator.type=frequency<100?'sine':'triangle';oscillator.frequency.value=frequency;envelope.gain.setValueAtTime(0,next);envelope.gain.linearRampToValueAtTime(gain,next+.012);envelope.gain.exponentialRampToValueAtTime(.0001,next+.32);oscillator.connect(envelope);envelope.connect(input);oscillator.start(next);oscillator.stop(next+.34);oscillator.onended=()=>{oscillator.disconnect();envelope.disconnect();};}next+=.38;beat++;}};tick();schedule=setInterval(tick,100);say('节奏正在驱动画面','The rhythm is driving the visual');render();}catch{stopAudio(false);say('点击后仍无法播放，请选择本地音频','Playback is unavailable. Choose local audio.');}}
 async function microphone(){let generation=-1;if(!navigator.mediaDevices?.getUserMedia){say('麦克风需要 HTTPS 或本机预览环境','Microphone access requires HTTPS or localhost.');return;}try{generation=await setupAudio();if(dead||generation!==audioGeneration)return;say('请允许使用麦克风','Allow microphone access to continue');const next=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});if(dead||generation!==audioGeneration){next.getTracks().forEach(track=>track.stop());return;}stream=next;const source=context!.createMediaStreamSource(next);source.connect(analyser!);nodes.push(source);root!.dataset.audioMode='microphone';paused=false;sync();say('麦克风已开启，试着说话或播放声音','Microphone enabled. Try speaking or playing sound.');render();}catch{if(dead||generation!==audioGeneration)return;stopAudio(false);say('未启用麦克风，可体验节奏或上传音频','Microphone not enabled. Try the rhythm or upload audio.');}}
 file.addEventListener('change',async()=>{const selected=file.files?.[0];if(!selected)return;let generation=-1;try{generation=await setupAudio();if(dead||generation!==audioGeneration)return;say('正在读取音频','Reading audio');const buffer=await context!.decodeAudioData(await selected.arrayBuffer());if(dead||generation!==audioGeneration)return;const source=context!.createBufferSource();source.buffer=buffer;source.loop=true;source.connect(analyser!);analyser!.connect(monitor!);monitor!.connect(context!.destination);nodes.push(source);source.start();root!.dataset.audioMode='file';paused=false;sync();say('正在播放：'+selected.name,'Playing: '+selected.name);render();}catch{if(dead||generation!==audioGeneration)return;stopAudio(false);say('无法读取此音频，请选择其他文件','Unable to read this audio. Choose another file.');}finally{file.value='';}},{signal:abort.signal});
 for(const b of buttons)b.addEventListener('click',()=>{const name=b.dataset.metAction;if(name==='demo')void demo();if(name==='microphone'){if(root!.dataset.audioMode==='microphone')stopAudio();else void microphone();}if(name==='stop')stopAudio();if(name==='pause'){paused=!paused;sync();render();}if(name==='reset'){yaw=0;pitch=0;time=0;renderer?.draw(time,signal,yaw,pitch);render();}if(name==='fullscreen'){if(document.fullscreenElement===root)void document.exitFullscreen();else void root!.requestFullscreen().catch(()=>{});}},{signal:abort.signal});
 volume.addEventListener('input',()=>{if(monitor&&context)monitor.gain.setTargetAtTime(Number(volume.value)/100,context.currentTime,.03);},{signal:abort.signal});
 let pointer:{id:number;x:number;y:number}|null=null;
 canvas.addEventListener('pointerdown',e=>{if(e.button!==0||!renderer)return;canvas.focus({preventScroll:true});pointer={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);},{signal:abort.signal});
 canvas.addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;yaw+=(e.clientX-pointer.x)*.005;pitch=Math.max(-1.2,Math.min(1.2,pitch+(e.clientY-pointer.y)*.005));pointer.x=e.clientX;pointer.y=e.clientY;renderer?.draw(time,signal,yaw,pitch);render();},{signal:abort.signal});
 const release=(e:PointerEvent)=>{if(pointer?.id===e.pointerId)pointer=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);};canvas.addEventListener('pointerup',release,{signal:abort.signal});canvas.addEventListener('pointercancel',release,{signal:abort.signal});
 canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','r','R'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')yaw-=.12;if(e.key==='ArrowRight')yaw+=.12;if(e.key==='ArrowUp')pitch-=.12;if(e.key==='ArrowDown')pitch+=.12;if(e.key.toLowerCase()==='r'){yaw=0;pitch=0;}renderer?.draw(time,signal,yaw,pitch);render();},{signal:abort.signal});
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(raf);raf=0;stopAudio(false);say('画面已暂停，请刷新以恢复交互','The scene paused. Reload to restore the interaction.');},{signal:abort.signal});
 const preloader=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){void load();preloader.disconnect();}},{rootMargin:'250px'});preloader.observe(root);
 const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible&&!suspended){if(context?.state==='suspended')void context.resume();render();}else{cancelAnimationFrame(raf);raf=0;last=0;if(context?.state==='running')void context.suspend();}},{threshold:.03});observer.observe(canvas);
 const resize=new ResizeObserver(()=>{renderer?.resize();if(renderer)renderer.draw(time,signal,yaw,pitch);render();});resize.observe(canvas);
 addEventListener('portfolio:scene-pause',()=>{suspended=true;cancelAnimationFrame(raf);raf=0;last=0;if(context?.state==='running')void context.suspend();},{signal:abort.signal});
 addEventListener('portfolio:scene-resume',()=>{suspended=false;last=0;if(visible&&!document.hidden){if(context?.state==='suspended')void context.resume();render();}},{signal:abort.signal});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;last=0;if(context?.state==='running')void context.suspend();}else if(visible&&!suspended){if(context?.state==='suspended')void context.resume();render();}},{signal:abort.signal});
 disposeAll=()=>{dead=true;stopAudio(false);abort.abort();cancelAnimationFrame(raf);preloader.disconnect();observer.disconnect();resize.disconnect();renderer?.dispose();active=null;disposeAll=null;};
}
addEventListener('portfolio:page-leave',()=>disposeAll?.());


